export * from './IDashboard'
export * from './ICategory'
export * from './IProduct'
export * from './ITag'
export * from './ISquare'
export * from './IMedia'
export * from './IUpload'
export * from './ICheck'
export * from './ILink'
export * from './IError'
export * from "./IAddImage";
export * from "./ICartShop";